// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: Coordination.proto

//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package exec

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DrillbitEndpoint_State int32

const (
	DrillbitEndpoint_STARTUP   DrillbitEndpoint_State = 0
	DrillbitEndpoint_ONLINE    DrillbitEndpoint_State = 1
	DrillbitEndpoint_QUIESCENT DrillbitEndpoint_State = 2
	DrillbitEndpoint_OFFLINE   DrillbitEndpoint_State = 3
)

// Enum value maps for DrillbitEndpoint_State.
var (
	DrillbitEndpoint_State_name = map[int32]string{
		0: "STARTUP",
		1: "ONLINE",
		2: "QUIESCENT",
		3: "OFFLINE",
	}
	DrillbitEndpoint_State_value = map[string]int32{
		"STARTUP":   0,
		"ONLINE":    1,
		"QUIESCENT": 2,
		"OFFLINE":   3,
	}
)

func (x DrillbitEndpoint_State) Enum() *DrillbitEndpoint_State {
	p := new(DrillbitEndpoint_State)
	*p = x
	return p
}

func (x DrillbitEndpoint_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DrillbitEndpoint_State) Descriptor() protoreflect.EnumDescriptor {
	return file_Coordination_proto_enumTypes[0].Descriptor()
}

func (DrillbitEndpoint_State) Type() protoreflect.EnumType {
	return &file_Coordination_proto_enumTypes[0]
}

func (x DrillbitEndpoint_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DrillbitEndpoint_State) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DrillbitEndpoint_State(num)
	return nil
}

// Deprecated: Use DrillbitEndpoint_State.Descriptor instead.
func (DrillbitEndpoint_State) EnumDescriptor() ([]byte, []int) {
	return file_Coordination_proto_rawDescGZIP(), []int{0, 0}
}

type DrillbitEndpoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     *string                 `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	UserPort    *int32                  `protobuf:"varint,2,opt,name=user_port,json=userPort" json:"user_port,omitempty"`
	ControlPort *int32                  `protobuf:"varint,3,opt,name=control_port,json=controlPort" json:"control_port,omitempty"`
	DataPort    *int32                  `protobuf:"varint,4,opt,name=data_port,json=dataPort" json:"data_port,omitempty"`
	Roles       *Roles                  `protobuf:"bytes,5,opt,name=roles" json:"roles,omitempty"`
	Version     *string                 `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
	State       *DrillbitEndpoint_State `protobuf:"varint,7,opt,name=state,enum=exec.DrillbitEndpoint_State" json:"state,omitempty"`
	HttpPort    *int32                  `protobuf:"varint,8,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
}

func (x *DrillbitEndpoint) Reset() {
	*x = DrillbitEndpoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Coordination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrillbitEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrillbitEndpoint) ProtoMessage() {}

func (x *DrillbitEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_Coordination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrillbitEndpoint.ProtoReflect.Descriptor instead.
func (*DrillbitEndpoint) Descriptor() ([]byte, []int) {
	return file_Coordination_proto_rawDescGZIP(), []int{0}
}

func (x *DrillbitEndpoint) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *DrillbitEndpoint) GetUserPort() int32 {
	if x != nil && x.UserPort != nil {
		return *x.UserPort
	}
	return 0
}

func (x *DrillbitEndpoint) GetControlPort() int32 {
	if x != nil && x.ControlPort != nil {
		return *x.ControlPort
	}
	return 0
}

func (x *DrillbitEndpoint) GetDataPort() int32 {
	if x != nil && x.DataPort != nil {
		return *x.DataPort
	}
	return 0
}

func (x *DrillbitEndpoint) GetRoles() *Roles {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *DrillbitEndpoint) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *DrillbitEndpoint) GetState() DrillbitEndpoint_State {
	if x != nil && x.State != nil {
		return *x.State
	}
	return DrillbitEndpoint_STARTUP
}

func (x *DrillbitEndpoint) GetHttpPort() int32 {
	if x != nil && x.HttpPort != nil {
		return *x.HttpPort
	}
	return 0
}

type DrillServiceInstance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  *string           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RegistrationTimeUTC *int64            `protobuf:"varint,2,opt,name=registrationTimeUTC" json:"registrationTimeUTC,omitempty"`
	Endpoint            *DrillbitEndpoint `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (x *DrillServiceInstance) Reset() {
	*x = DrillServiceInstance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Coordination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrillServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrillServiceInstance) ProtoMessage() {}

func (x *DrillServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_Coordination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrillServiceInstance.ProtoReflect.Descriptor instead.
func (*DrillServiceInstance) Descriptor() ([]byte, []int) {
	return file_Coordination_proto_rawDescGZIP(), []int{1}
}

func (x *DrillServiceInstance) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *DrillServiceInstance) GetRegistrationTimeUTC() int64 {
	if x != nil && x.RegistrationTimeUTC != nil {
		return *x.RegistrationTimeUTC
	}
	return 0
}

func (x *DrillServiceInstance) GetEndpoint() *DrillbitEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type Roles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SqlQuery         *bool `protobuf:"varint,1,opt,name=sql_query,json=sqlQuery,def=1" json:"sql_query,omitempty"`
	LogicalPlan      *bool `protobuf:"varint,2,opt,name=logical_plan,json=logicalPlan,def=1" json:"logical_plan,omitempty"`
	PhysicalPlan     *bool `protobuf:"varint,3,opt,name=physical_plan,json=physicalPlan,def=1" json:"physical_plan,omitempty"`
	JavaExecutor     *bool `protobuf:"varint,4,opt,name=java_executor,json=javaExecutor,def=1" json:"java_executor,omitempty"`
	DistributedCache *bool `protobuf:"varint,5,opt,name=distributed_cache,json=distributedCache,def=1" json:"distributed_cache,omitempty"`
}

// Default values for Roles fields.
const (
	Default_Roles_SqlQuery         = bool(true)
	Default_Roles_LogicalPlan      = bool(true)
	Default_Roles_PhysicalPlan     = bool(true)
	Default_Roles_JavaExecutor     = bool(true)
	Default_Roles_DistributedCache = bool(true)
)

func (x *Roles) Reset() {
	*x = Roles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Coordination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roles) ProtoMessage() {}

func (x *Roles) ProtoReflect() protoreflect.Message {
	mi := &file_Coordination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roles.ProtoReflect.Descriptor instead.
func (*Roles) Descriptor() ([]byte, []int) {
	return file_Coordination_proto_rawDescGZIP(), []int{2}
}

func (x *Roles) GetSqlQuery() bool {
	if x != nil && x.SqlQuery != nil {
		return *x.SqlQuery
	}
	return Default_Roles_SqlQuery
}

func (x *Roles) GetLogicalPlan() bool {
	if x != nil && x.LogicalPlan != nil {
		return *x.LogicalPlan
	}
	return Default_Roles_LogicalPlan
}

func (x *Roles) GetPhysicalPlan() bool {
	if x != nil && x.PhysicalPlan != nil {
		return *x.PhysicalPlan
	}
	return Default_Roles_PhysicalPlan
}

func (x *Roles) GetJavaExecutor() bool {
	if x != nil && x.JavaExecutor != nil {
		return *x.JavaExecutor
	}
	return Default_Roles_JavaExecutor
}

func (x *Roles) GetDistributedCache() bool {
	if x != nil && x.DistributedCache != nil {
		return *x.DistributedCache
	}
	return Default_Roles_DistributedCache
}

var File_Coordination_proto protoreflect.FileDescriptor

var file_Coordination_proto_rawDesc = []byte{
	0x0a, 0x12, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x78, 0x65, 0x63, 0x22, 0xd5, 0x02, 0x0a, 0x10, 0x44,
	0x72, 0x69, 0x6c, 0x6c, 0x62, 0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x61, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x44, 0x72, 0x69, 0x6c, 0x6c, 0x62,
	0x69, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x74, 0x74, 0x70, 0x5f,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70,
	0x50, 0x6f, 0x72, 0x74, 0x22, 0x3c, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x55, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x51, 0x55, 0x49, 0x45, 0x53, 0x43,
	0x45, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e, 0x45,
	0x10, 0x03, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x44, 0x72, 0x69, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x13, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x55,
	0x54, 0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x54, 0x43, 0x12, 0x32, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x44, 0x72, 0x69, 0x6c, 0x6c, 0x62, 0x69, 0x74, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x22, 0xdc, 0x01, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x09, 0x73,
	0x71, 0x6c, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x04,
	0x74, 0x72, 0x75, 0x65, 0x52, 0x08, 0x73, 0x71, 0x6c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x27,
	0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69,
	0x63, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x29, 0x0a, 0x0d, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x04,
	0x74, 0x72, 0x75, 0x65, 0x52, 0x0c, 0x70, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x6c,
	0x61, 0x6e, 0x12, 0x29, 0x0a, 0x0d, 0x6a, 0x61, 0x76, 0x61, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52,
	0x0c, 0x6a, 0x61, 0x76, 0x61, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a,
	0x11, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x10,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x42, 0x6a, 0x0a, 0x1b, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x64,
	0x72, 0x69, 0x6c, 0x6c, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42,
	0x12, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x73, 0x68, 0x61, 0x64, 0x65, 0x2f, 0x67, 0x6f, 0x2d, 0x64,
	0x72, 0x69, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x65, 0x63,
}

var (
	file_Coordination_proto_rawDescOnce sync.Once
	file_Coordination_proto_rawDescData = file_Coordination_proto_rawDesc
)

func file_Coordination_proto_rawDescGZIP() []byte {
	file_Coordination_proto_rawDescOnce.Do(func() {
		file_Coordination_proto_rawDescData = protoimpl.X.CompressGZIP(file_Coordination_proto_rawDescData)
	})
	return file_Coordination_proto_rawDescData
}

var file_Coordination_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Coordination_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_Coordination_proto_goTypes = []interface{}{
	(DrillbitEndpoint_State)(0),  // 0: exec.DrillbitEndpoint.State
	(*DrillbitEndpoint)(nil),     // 1: exec.DrillbitEndpoint
	(*DrillServiceInstance)(nil), // 2: exec.DrillServiceInstance
	(*Roles)(nil),                // 3: exec.Roles
}
var file_Coordination_proto_depIdxs = []int32{
	3, // 0: exec.DrillbitEndpoint.roles:type_name -> exec.Roles
	0, // 1: exec.DrillbitEndpoint.state:type_name -> exec.DrillbitEndpoint.State
	1, // 2: exec.DrillServiceInstance.endpoint:type_name -> exec.DrillbitEndpoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_Coordination_proto_init() }
func file_Coordination_proto_init() {
	if File_Coordination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Coordination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrillbitEndpoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Coordination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrillServiceInstance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Coordination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Coordination_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Coordination_proto_goTypes,
		DependencyIndexes: file_Coordination_proto_depIdxs,
		EnumInfos:         file_Coordination_proto_enumTypes,
		MessageInfos:      file_Coordination_proto_msgTypes,
	}.Build()
	File_Coordination_proto = out.File
	file_Coordination_proto_rawDesc = nil
	file_Coordination_proto_goTypes = nil
	file_Coordination_proto_depIdxs = nil
}
