// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: SchemaDef.proto

//
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package exec

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/factset/go-drill/internal/rpc/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ValueMode int32

const (
	ValueMode_VALUE_VECTOR ValueMode = 0
	ValueMode_RLE          ValueMode = 1
	ValueMode_DICT         ValueMode = 2
)

// Enum value maps for ValueMode.
var (
	ValueMode_name = map[int32]string{
		0: "VALUE_VECTOR",
		1: "RLE",
		2: "DICT",
	}
	ValueMode_value = map[string]int32{
		"VALUE_VECTOR": 0,
		"RLE":          1,
		"DICT":         2,
	}
)

func (x ValueMode) Enum() *ValueMode {
	p := new(ValueMode)
	*p = x
	return p
}

func (x ValueMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueMode) Descriptor() protoreflect.EnumDescriptor {
	return file_SchemaDef_proto_enumTypes[0].Descriptor()
}

func (ValueMode) Type() protoreflect.EnumType {
	return &file_SchemaDef_proto_enumTypes[0]
}

func (x ValueMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ValueMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ValueMode(num)
	return nil
}

// Deprecated: Use ValueMode.Descriptor instead.
func (ValueMode) EnumDescriptor() ([]byte, []int) {
	return file_SchemaDef_proto_rawDescGZIP(), []int{0}
}

var File_SchemaDef_proto protoreflect.FileDescriptor

var file_SchemaDef_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x65, 0x78, 0x65, 0x63, 0x1a, 0x0b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x30, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x5f, 0x56, 0x45, 0x43, 0x54, 0x4f,
	0x52, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x49, 0x43, 0x54, 0x10, 0x02, 0x42, 0x67, 0x0a, 0x1b, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x64, 0x72, 0x69, 0x6c, 0x6c, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x44, 0x65, 0x66,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x48, 0x01, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x72, 0x6f, 0x73, 0x68, 0x61, 0x64, 0x65, 0x2f, 0x67,
	0x6f, 0x2d, 0x64, 0x72, 0x69, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x78, 0x65, 0x63,
}

var (
	file_SchemaDef_proto_rawDescOnce sync.Once
	file_SchemaDef_proto_rawDescData = file_SchemaDef_proto_rawDesc
)

func file_SchemaDef_proto_rawDescGZIP() []byte {
	file_SchemaDef_proto_rawDescOnce.Do(func() {
		file_SchemaDef_proto_rawDescData = protoimpl.X.CompressGZIP(file_SchemaDef_proto_rawDescData)
	})
	return file_SchemaDef_proto_rawDescData
}

var file_SchemaDef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SchemaDef_proto_goTypes = []interface{}{
	(ValueMode)(0), // 0: exec.ValueMode
}
var file_SchemaDef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SchemaDef_proto_init() }
func file_SchemaDef_proto_init() {
	if File_SchemaDef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SchemaDef_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SchemaDef_proto_goTypes,
		DependencyIndexes: file_SchemaDef_proto_depIdxs,
		EnumInfos:         file_SchemaDef_proto_enumTypes,
	}.Build()
	File_SchemaDef_proto = out.File
	file_SchemaDef_proto_rawDesc = nil
	file_SchemaDef_proto_goTypes = nil
	file_SchemaDef_proto_depIdxs = nil
}
