// Code generated by vector_numeric.gen.go.tmpl. DO NOT EDIT.

package data

import (
	"reflect"

	"github.com/factset/go-drill/internal/rpc/proto/exec/shared"
)

// Int64 vector

type Int64Vector struct {
	vector
	values []int64
	meta   *shared.SerializedField
}

func (Int64Vector) Type() reflect.Type {
	return reflect.TypeOf(int64(0))
}

func (Int64Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Int64Vector) Len() int {
	return int(len(v.values))
}

func (v *Int64Vector) Get(index uint) int64 {
	return v.values[index]
}

func (v *Int64Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewInt64Vector(data []byte, meta *shared.SerializedField) *Int64Vector {
	return &Int64Vector{
		vector: vector{rawData: data},
		values: Int64Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableInt64Vector struct {
	*Int64Vector

	nullByteMap
}

func (nv *NullableInt64Vector) Get(index uint) *int64 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableInt64Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableInt64Vector(data []byte, meta *shared.SerializedField) *NullableInt64Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableInt64Vector{
		NewInt64Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Int32 vector

type Int32Vector struct {
	vector
	values []int32
	meta   *shared.SerializedField
}

func (Int32Vector) Type() reflect.Type {
	return reflect.TypeOf(int32(0))
}

func (Int32Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Int32Vector) Len() int {
	return int(len(v.values))
}

func (v *Int32Vector) Get(index uint) int32 {
	return v.values[index]
}

func (v *Int32Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewInt32Vector(data []byte, meta *shared.SerializedField) *Int32Vector {
	return &Int32Vector{
		vector: vector{rawData: data},
		values: Int32Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableInt32Vector struct {
	*Int32Vector

	nullByteMap
}

func (nv *NullableInt32Vector) Get(index uint) *int32 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableInt32Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableInt32Vector(data []byte, meta *shared.SerializedField) *NullableInt32Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableInt32Vector{
		NewInt32Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Float64 vector

type Float64Vector struct {
	vector
	values []float64
	meta   *shared.SerializedField
}

func (Float64Vector) Type() reflect.Type {
	return reflect.TypeOf(float64(0))
}

func (Float64Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Float64Vector) Len() int {
	return int(len(v.values))
}

func (v *Float64Vector) Get(index uint) float64 {
	return v.values[index]
}

func (v *Float64Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewFloat64Vector(data []byte, meta *shared.SerializedField) *Float64Vector {
	return &Float64Vector{
		vector: vector{rawData: data},
		values: Float64Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableFloat64Vector struct {
	*Float64Vector

	nullByteMap
}

func (nv *NullableFloat64Vector) Get(index uint) *float64 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableFloat64Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableFloat64Vector(data []byte, meta *shared.SerializedField) *NullableFloat64Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableFloat64Vector{
		NewFloat64Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Uint64 vector

type Uint64Vector struct {
	vector
	values []uint64
	meta   *shared.SerializedField
}

func (Uint64Vector) Type() reflect.Type {
	return reflect.TypeOf(uint64(0))
}

func (Uint64Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Uint64Vector) Len() int {
	return int(len(v.values))
}

func (v *Uint64Vector) Get(index uint) uint64 {
	return v.values[index]
}

func (v *Uint64Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewUint64Vector(data []byte, meta *shared.SerializedField) *Uint64Vector {
	return &Uint64Vector{
		vector: vector{rawData: data},
		values: Uint64Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableUint64Vector struct {
	*Uint64Vector

	nullByteMap
}

func (nv *NullableUint64Vector) Get(index uint) *uint64 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableUint64Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableUint64Vector(data []byte, meta *shared.SerializedField) *NullableUint64Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableUint64Vector{
		NewUint64Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Uint32 vector

type Uint32Vector struct {
	vector
	values []uint32
	meta   *shared.SerializedField
}

func (Uint32Vector) Type() reflect.Type {
	return reflect.TypeOf(uint32(0))
}

func (Uint32Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Uint32Vector) Len() int {
	return int(len(v.values))
}

func (v *Uint32Vector) Get(index uint) uint32 {
	return v.values[index]
}

func (v *Uint32Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewUint32Vector(data []byte, meta *shared.SerializedField) *Uint32Vector {
	return &Uint32Vector{
		vector: vector{rawData: data},
		values: Uint32Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableUint32Vector struct {
	*Uint32Vector

	nullByteMap
}

func (nv *NullableUint32Vector) Get(index uint) *uint32 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableUint32Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableUint32Vector(data []byte, meta *shared.SerializedField) *NullableUint32Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableUint32Vector{
		NewUint32Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Float32 vector

type Float32Vector struct {
	vector
	values []float32
	meta   *shared.SerializedField
}

func (Float32Vector) Type() reflect.Type {
	return reflect.TypeOf(float32(0))
}

func (Float32Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Float32Vector) Len() int {
	return int(len(v.values))
}

func (v *Float32Vector) Get(index uint) float32 {
	return v.values[index]
}

func (v *Float32Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewFloat32Vector(data []byte, meta *shared.SerializedField) *Float32Vector {
	return &Float32Vector{
		vector: vector{rawData: data},
		values: Float32Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableFloat32Vector struct {
	*Float32Vector

	nullByteMap
}

func (nv *NullableFloat32Vector) Get(index uint) *float32 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableFloat32Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableFloat32Vector(data []byte, meta *shared.SerializedField) *NullableFloat32Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableFloat32Vector{
		NewFloat32Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Int16 vector

type Int16Vector struct {
	vector
	values []int16
	meta   *shared.SerializedField
}

func (Int16Vector) Type() reflect.Type {
	return reflect.TypeOf(int16(0))
}

func (Int16Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Int16Vector) Len() int {
	return int(len(v.values))
}

func (v *Int16Vector) Get(index uint) int16 {
	return v.values[index]
}

func (v *Int16Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewInt16Vector(data []byte, meta *shared.SerializedField) *Int16Vector {
	return &Int16Vector{
		vector: vector{rawData: data},
		values: Int16Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableInt16Vector struct {
	*Int16Vector

	nullByteMap
}

func (nv *NullableInt16Vector) Get(index uint) *int16 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableInt16Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableInt16Vector(data []byte, meta *shared.SerializedField) *NullableInt16Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableInt16Vector{
		NewInt16Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Uint16 vector

type Uint16Vector struct {
	vector
	values []uint16
	meta   *shared.SerializedField
}

func (Uint16Vector) Type() reflect.Type {
	return reflect.TypeOf(uint16(0))
}

func (Uint16Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Uint16Vector) Len() int {
	return int(len(v.values))
}

func (v *Uint16Vector) Get(index uint) uint16 {
	return v.values[index]
}

func (v *Uint16Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewUint16Vector(data []byte, meta *shared.SerializedField) *Uint16Vector {
	return &Uint16Vector{
		vector: vector{rawData: data},
		values: Uint16Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableUint16Vector struct {
	*Uint16Vector

	nullByteMap
}

func (nv *NullableUint16Vector) Get(index uint) *uint16 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableUint16Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableUint16Vector(data []byte, meta *shared.SerializedField) *NullableUint16Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableUint16Vector{
		NewUint16Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Int8 vector

type Int8Vector struct {
	vector
	values []int8
	meta   *shared.SerializedField
}

func (Int8Vector) Type() reflect.Type {
	return reflect.TypeOf(int8(0))
}

func (Int8Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Int8Vector) Len() int {
	return int(len(v.values))
}

func (v *Int8Vector) Get(index uint) int8 {
	return v.values[index]
}

func (v *Int8Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewInt8Vector(data []byte, meta *shared.SerializedField) *Int8Vector {
	return &Int8Vector{
		vector: vector{rawData: data},
		values: Int8Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableInt8Vector struct {
	*Int8Vector

	nullByteMap
}

func (nv *NullableInt8Vector) Get(index uint) *int8 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableInt8Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableInt8Vector(data []byte, meta *shared.SerializedField) *NullableInt8Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableInt8Vector{
		NewInt8Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}

// Uint8 vector

type Uint8Vector struct {
	vector
	values []uint8
	meta   *shared.SerializedField
}

func (Uint8Vector) Type() reflect.Type {
	return reflect.TypeOf(uint8(0))
}

func (Uint8Vector) TypeLen() (int64, bool) {
	return 0, false
}

func (v *Uint8Vector) Len() int {
	return int(len(v.values))
}

func (v *Uint8Vector) Get(index uint) uint8 {
	return v.values[index]
}

func (v *Uint8Vector) Value(index uint) interface{} {
	return v.Get(index)
}

func NewUint8Vector(data []byte, meta *shared.SerializedField) *Uint8Vector {
	return &Uint8Vector{
		vector: vector{rawData: data},
		values: Uint8Traits.CastFromBytes(data),
		meta:   meta,
	}
}

type NullableUint8Vector struct {
	*Uint8Vector

	nullByteMap
}

func (nv *NullableUint8Vector) Get(index uint) *uint8 {
	if nv.IsNull(index) {
		return nil
	}

	return &nv.values[index]
}

func (nv *NullableUint8Vector) Value(index uint) interface{} {
	val := nv.Get(index)
	if val != nil {
		return *val
	}

	return val
}

func NewNullableUint8Vector(data []byte, meta *shared.SerializedField) *NullableUint8Vector {
	byteMap := data[:meta.GetValueCount()]
	remaining := data[meta.GetValueCount():]

	return &NullableUint8Vector{
		NewUint8Vector(remaining, meta),
		nullByteMap{byteMap},
	}
}
